ShoppingCart/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;
using System.Linq;
using System.Diagnostics;
using System.Threading.Tasks;
using ShoppingCart.Models;
using Microsoft.EntityFrameworkCore;

namespace ShoppingCart.Controllers
{
    public class CartController : Controller
    {
        private readonly DBContext db;

        public CartController(DBContext dbContext)
        {

            this.db = dbContext;

        }

        public IActionResult Index()
        {

            Customer currentCustomer = CheckLoggedIn();

            Dictionary<Product, int> countOfItems = new Dictionary<Product, int>();
            List<Cart> customerCart = new List<Cart>();
            List<GuestCart> guestCart = new List<GuestCart>();
            //Seed an item for user
            if (currentCustomer != null)
            {

                Product newProd = FetchRandomProduct();

                db.SaveChanges();

                customerCart = db.Carts.Where(x => x.CustomerId == currentCustomer.Id).ToList();

                foreach (Cart item in customerCart)
                {
                    Product newItem = db.Products.FirstOrDefault(x => x.Id == item.ProductId);
                    countOfItems.Add(newItem, item.OrderQty);
                };

                ViewBag.CurrentUserName = currentCustomer.FullName;

            }
            else
            {

                Product newProd = FetchRandomProduct();

                db.SaveChanges();

                guestCart = db.GuestCarts.ToList();

                foreach (GuestCart item in guestCart)
                {
                    Product newItem = db.Products.FirstOrDefault(x => x.Id == item.ProductId);
                    countOfItems.Add(newItem, item.OrderQty);
                };
                ViewBag.CurrentUserName = "Guest User";

            }

            //initializing

            ViewBag.CurrentCustomer = currentCustomer;
            ViewBag.CountOfItems = countOfItems;
            ViewBag.TotalPrice = CalculateTotalPrice();
            ViewBag.CartContents = CountNumberOfItems();
            return View();
        }
        //remove item from cart using JSON
        public IActionResult RemoveItem([FromBody] ProdJson prodJson)
        {
            string ProductName = prodJson.ProductName;            
            SubtractFromCart(ProductName);
            return Json(new { isOkay = true });

        }
        //Add item to cart using JSON
        public IActionResult AddItem([FromBody] ProdJson prodJson)
        {
            string ProductName = prodJson.ProductName;            
            AddToCart(ProductName);
            return Json(new { isOkay = true });
        }

        public IActionResult RemoveProduct([FromBody] ProdJson prodJson)
        {
            string ProductName = prodJson.ProductName;
            RemoveProdctFromCart(ProductName);
            return Json(new { isOkay = true });
        }

        //AddToCart (will be used in the gallery, the cart page and the results page)
        public void AddToCart(string productName)
        {
            //check for the current product in the database
            Product newProd = db.Products.FirstOrDefault(x => x.ProductName == productName);

            Customer currentCustomer = CheckLoggedIn();            
            if (currentCustomer != null)
            {
                Cart itemInCart = db.Carts.FirstOrDefault(x => x.ProductId == newProd.Id && x.CustomerId == currentCustomer.Id);

                //query in the database whether the item already exists in the shopping cart of the customer
                if (itemInCart == null)
                {
                    //if not, create a new entry
                    db.Carts.Add(new Cart
                    {
                        ProductId = newProd.Id,
                        CustomerId = currentCustomer.Id,
                        OrderQty = 1
                    });
                }
                else
                {
                    //if found, add 1 to the product quantity
                    itemInCart.OrderQty++;
                }
                db.SaveChanges();
            }
            else {

                GuestCart itemInCart = db.GuestCarts.FirstOrDefault(x => x.ProductId == newProd.Id);

                //query in the database whether the item already exists in the shopping cart of the customer
                if (itemInCart == null)
                {
                    //if not, create a new entry
                    db.GuestCarts.Add(new GuestCart
                    {
                        ProductId = newProd.Id,
                        OrderQty = 1
                    });
                }
                else
                {
                    //if found, add 1 to the product quantity
                    itemInCart.OrderQty++;
                }
                db.SaveChanges();
            }
        }

        //remove the entore product from the cart
        public void RemoveProdctFromCart(string productName)
        {
            Product newProd = db.Products.FirstOrDefault(x => x.ProductName == productName);

            Customer currentCustomer = CheckLoggedIn();

            if (currentCustomer != null)
            {
                Cart itemInCart = db.Carts.FirstOrDefault(x => x.ProductId == newProd.Id && x.CustomerId == currentCustomer.Id);
                                
                    db.Carts.Remove(itemInCart);                
                db.SaveChanges();
            }
            else
            {
                GuestCart itemInCart = db.GuestCarts.FirstOrDefault(x => x.ProductId == newProd.Id);
                                
                    db.GuestCarts.Remove(itemInCart);
                
                db.SaveChanges();
            }
        }

        //will be used in the cart page
        public void SubtractFromCart(string productName)
        {
            Product newProd = db.Products.FirstOrDefault(x => x.ProductName == productName);

            Customer currentCustomer = CheckLoggedIn();

            if (currentCustomer != null)
            {
                Cart itemInCart = db.Carts.FirstOrDefault(x => x.ProductId == newProd.Id && x.CustomerId == currentCustomer.Id);

                if (itemInCart.OrderQty == 1)
                {
                    db.Carts.Remove(itemInCart);
                }
                else
                {
                    itemInCart.OrderQty--;
                }
                db.SaveChanges();
            }
            else
            {

                GuestCart itemInCart = db.GuestCarts.FirstOrDefault(x => x.ProductId == newProd.Id);

                if (itemInCart.OrderQty == 1)
                {
                    db.GuestCarts.Remove(itemInCart);
                }
                else
                {
                    itemInCart.OrderQty--;
                }
                db.SaveChanges();
            }
        }
        public IActionResult Checkout()
        {
            Customer currentCustomer = CheckLoggedIn();

            if (currentCustomer != null)
            {
                //get all items in the cart under the customer
                List<Cart> itemsInCart = db.Carts.Where(x => x.CustomerId == currentCustomer.Id).ToList();

                //get all current purchases of customer
                //for display later in the checkout
                Dictionary<Product, int> itemQty = new Dictionary<Product, int>();
                
                //take the price of the entire list
                double totalPrice = CalculateTotalPrice();
                ViewBag.TotalPrice = totalPrice;

                //transform all items into purchases
                foreach (Cart item in itemsInCart)
                {
                    Purchase onHand = db.Purchases.FirstOrDefault(x => x.CustomerId == currentCustomer.Id && x.ProductId == item.ProductId);

                    if (onHand == null)
                    {
                        //if it is not in the purchases db, create new purchase, add activation code and set quantity to 1
                        onHand = new Purchase
                        {
                            ProductId = item.ProductId,
                            CustomerId = currentCustomer.Id,
                            PurchaseDate = DateTime.Now,
                            PurchaseQty = item.OrderQty
                        };
                        db.Purchases.Add(onHand);
                    }
                    else
                    {
                        //if it is, add to purchase qty
                        onHand.PurchaseQty += item.OrderQty;
                    }

                    db.SaveChanges();

                    for (int i = item.OrderQty; i > 0; i--)
                    {

                        //generate activation code
                        ActivationCode newCode = new ActivationCode
                        {
                            //put the attributes
                            ProductID = item.ProductId,
                            PurchaseID = onHand.Id
                        };

                        db.ActivationCodes.Add(newCode);

                        db.SaveChanges();
                    }

                    //remove from the ShoppingCarts database
                    Cart findTheItem = db.Carts.FirstOrDefault(x => x.Id == item.Id);
                    Product findProduct = db.Products.FirstOrDefault(x => x.Id == findTheItem.ProductId);
                    itemQty.Add(findProduct, findTheItem.OrderQty);

                    db.Carts.Remove(findTheItem);

ShoppingCart/Controllers/LogoutController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ShoppingCart.Models;
using Microsoft.EntityFrameworkCore;

namespace ShoppingCart.Controllers
{
    public class LogoutController : Controller
    {
        private DBContext dbContext;

        public LogoutController(DBContext dbContext)
        {
            
            this.dbContext = dbContext;
           
        }
        public IActionResult Index()
        {// remove session from our database
            if (Request.Cookies["SessionId"] != null)
            {//session Id is converted to string as our Session controller has PK in string type//
                //string sessionId = System.Guid.NewGuid().ToString();//
              Guid sessionId = Guid.Parse(Request.Cookies["sessionId"]);


                Session session = dbContext.Sessions.FirstOrDefault(x => x.Id == sessionId);
                if (session != null)
                {
                    // delete session record from our database;
                    dbContext.Remove(session);

                    // commit to save changes
                    dbContext.SaveChanges();
                }
            }

            // ask client to remove these cookies so that
            // they won't be sent over next time
            Response.Cookies.Delete("SessionId");
            Response.Cookies.Delete("Username");

            return RedirectToAction("Index", "Login");
        }
        
        
    }
}

ShoppingCart/Views/Shared/_Layout.cshtml
@{ 


}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Shopping Platform</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/Login.css" />

</head>
<body>
    <header>

        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a asp-area="" asp-controller="Gallery" asp-action="Index"><img src="/Logo/shopgood-logo.png"></a>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <span class="nav-link text-dark">Welcome, <b>@(ViewBag.CurrentUserName)!</b></span>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Gallery" asp-action="Index">Home</a>
                        </li>


                        @{
                            if (ViewBag.CurrentUserName == "Guest User")
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                                </li>
                            }
                            else
                            {

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Purchase" asp-action="Index">My Purchases</a>
                                </li>


                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Logout" asp-action="Index">Logout</a>
                                </li>
                            }
                        }

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">
                                <img src="/Logo/cart-icon-28356.png" height="25" , width="25">
                            </a>
                        </li>

                        <li class="nav-item">
                            <div style="border-radius: 20px; background-color: #ac2a2a">
                                <a style="color: white" class="nav-link" asp-area="" asp-controller="Cart" asp-action="Index" id="currentCartContents">@(ViewBag.CartContents)</a>
                            </div>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>

        <div>

            @RenderBody()

        </div>
    </div>

    <!--'Item added to the cart' custom pop-up model-->
    <div class="modal fade" id="ItemAdded" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">ShopGood</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Item added to the cart</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">OK</button>
                </div>
            </div>
        </div>
    </div>

    <!--'Please Rate the product' custom pop-up model-->
    <div class="modal fade" id="rateProduct" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">ShopGood</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Please rate the product</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">OK</button>
                </div>
            </div>
        </div>
    </div>

    <!--'Thank you for sharing your experience' custom pop-up model-->
    <div class="modal fade" id="reviewSubmitted" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">ShopGood</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Thank you for the rating and sharing your experience</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" id="purchases" onclick="setSubmitOK()">BACK TO PURCHASES</button>
                </div>
            </div>
        </div>
    </div>   

        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)

</body>

</html>